name: Build websitino (linux-static)

on:
  push:
    branches:
      - main

jobs:
  build-and-export:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker build
    - name: Build Docker image
      run: |
        echo "commit: ${GITHUB_SHA::7}" > version
        echo "FROM alpine:latest
        RUN apk add vim gcc musl-dev ldc dub llvm-libunwind-static openssl-libs-static gzip upx cmake make
        WORKDIR /app
        COPY . .
        CMD [\"dub\", \"build\", \"--build=release\", \"--config=linux-static\"]" > Dockerfile
        docker build -t websitino-image .

    # Run the Docker container to build the project
    - name: Run Docker container and build project
      run: |
        docker run --name websitino-container websitino-image || true

    # Copy compiled file from Docker container to host
    - name: Copy compiled binary
      run: |
        docker cp websitino-container:/app/websitino .
        docker rm websitino-container
        strip -s websitino

    # Upload the binary as an artifact
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: websitino
        path: websitino

    - name: Pull latest changes
      run: |
        git fetch origin
        git checkout gh-pages
        git pull origin gh-pages

    # Prepara la directory per GitHub Pages
    - name: Prepara directory per GitHub Pages
      run: |
        mkdir -p public/linux
        cp websitino public/linux/

    # Pubblica su GitHub Pages
    - name: Deploy su GitHub Pages
      if: startsWith(github.ref, 'refs/tags/v')
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: false
        keep_files: true