# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build websitino (windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        dc: [ldc-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Build & Test'
      run: |
        dub build --compiler=ldc2 --build=release --config=windows-static

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: websitino.exe
        path: websitino.exe

    - name: Pull latest changes
      run: |
        git fetch origin
        git checkout gh-pages
        git pull origin gh-pages

    - name: Prepara directory per GitHub Pages
      run: |
        mkdir -p public/windows
        cp websitino.exe public/windows/websitino.exe

    # Pubblica su GitHub Pages
    - name: Deploy su GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: false
        keep_files: true
